name: Deploy Function App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctioAppDeploymentTry'
          slot-name: 'production'
          package: ./Test_Functions
