name: Deploy Web App

on:
  push:
    branches:
      - main

env:
  WEB_PATH: ./Test_WebApp

jobs:
  deploy-web-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install npm packages
        run: |
          cd Test_WebApp
          npm install

      - name: Build Web App
        run: |
          cd Test_WebApp
          npm run build

      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'WebAppDeploymentTry'
          package: ${{ env.WEB_PATH }}/dist
