name: Deploy db

on:
  push:
    branches:
      - main

env:
  PACKAGE_PATH: ./Test_Functions
  WEB_PATH: ./Test_WebApp
  SUBSCRIPTION: 23dedca3-2d6f-4822-a69c-d354f6f9e298
  RESOURCEGROUP: FunctionResourceGroup

jobs:
  deploy-logic-app:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages
        run: nuget restore Test_db/Test_db.sqlproj

      - name: Build Web App
        run: |
          msbuild.exe Test_db/Test_db.sqlproj /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:OutDir="./outputs"
          
      - name: List Dacpac Files
        run: |
          cd .\outputs
          dir *.dacpac
