name: Deploy Function App and Web App

on:
  push:
    branches:
      - main

env:
  PACKAGE_PATH: ./Test_Functions
  WEB_PATH: ./Test_WebApp

jobs:
  deploy-web-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages
        run: nuget restore Test_WebApp/Test_WebApp.csproj

      - name: Build Web App
        run: |
          msbuild.exe Test_WebApp/Test_WebApp.csproj /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:OutDir="./outputs"

      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DeploymentWebAppTry'
          package: ${{ env.WEB_PATH }}/outputs
