name: Deploy Function App and Web App

on:
  push:
    branches:
      - main

env:
  PACKAGE_PATH: ./Test_Functions
  WEB_PATH: ./Test_WebApp
  SUBSCRIPTION: 23dedca3-2d6f-4822-a69c-d354f6f9e298
  RESOURCEGROUP: FunctionResourceGroup

jobs:
  deploy-logic-app:
   # needs: deploy-function-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Logic App
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION }}
          resourceGroupName: ${{ env.RESOURCEGROUP }}
          template: ./Test_Logic/LogicApp.json
          parameters: ./Test_Logic/LogicApp.parameters.json
