name: Deploy Function App, Web App, and Logic App

on:
  push:
    branches:
      - main

env:
  PACKAGE_PATH: ./Test_Functions
  WEB_PATH: ./Test_WebApp
  SUBSCRIPTION: 23dedca3-2d6f-4822-a69c-d354f6f9e298
  RESOURCEGROUP: FunctionResourceGroup

jobs:
  deploy-function-app:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages
        run: nuget restore Test_Functions/Test_Functions.csproj

      - name: Build Function App
        run: |
          msbuild.exe Test_Functions/Test_Functions.csproj /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:OutDir="./output"

      - name: Deploy Function App
        uses: azure/functions-action@v1
        with:
          app-name: 'FunctionAppDeploymentTry'
          package: ${{ env.PACKAGE_PATH }}/output

  deploy-web-app:
    needs: deploy-function-app
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages
        run: nuget restore Test_WebApp/Test_WebApp.csproj

      - name: Build Web App
        run: |
          msbuild.exe Test_WebApp/Test_WebApp.csproj /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:OutDir="./outputs"

      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DeploymentWebAppTry'
          package: ${{ env.WEB_PATH }}/outputs

  deploy-logic-app:
    needs: deploy-web-app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Logic App
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION }}
          resourceGroupName: ${{ env.RESOURCEGROUP }}
          template: ./Test_Logic/LogicApp.json
          parameters: ./Test_Logic/LogicApp.parameters.json
